development: &development
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: restaurant_dev
  pool: 5
  username: root
  password: 
  host: localhost
test:
  <<: *development
  database: restaurant_test
staging:
  <<: *development
  database: restaurant_staging

